### ISSUE TITLE
-y option still prompting user for password

### ISSUE THREAD

**Issue by lbesnard** [Laharah/redlist#5]
Hi, I only discovered your script recently and absolutely love it. I've been wanting this for a long time.

I have a script calling redlist to update all my playlists. However, redlist always ask for some user input even with the -y option.
Here is my config:
```yaml
beets_library: /.../musiclibrary2.blb
torrent_directory: .
m3u_directory: /.../playlists_navidrome
pinentry: yes
enable_deluge: no
restrict_album: no
overwrite_m3u: yes
```

Basically, it tries to connect to [REDACTED] (i'm still confused about what redacted is, is it jackett? or something similar?). But since in my config, I disabled deluge, I don't expect any music search to happen on various trackers. But redlist is prompting me for a username/password. 
```
Connecting to [REDACTED]...
[REDACTED] Username:
Search Canceled.
ERROR:asyncio:Unclosed client session
```

How can I disable this?

(EDIT: found what redacted is, makes more sense now)
